image: gitlab-registry.irstea.fr/francois.colleoni/smash:latest
  
stages:
  - tap-cmp
  - build-code
  - build-doc
  - test
  
tap-cmp:
  stage: tap-cmp
  script:
    - make tap_cmp

build-code:
  stage: build-code
  script: 
    - make
  artifacts:
    paths:
      - smash/
    expire_in: 1 hour

build-doc:
  stage: build-doc
  script:
    - make library
    - make doc

test:
  stage: test
  script:
    - make library
    - make test
