name: smash
channels:
    - conda-forge
dependencies:
    - python=3.8
    - pip
    
    # compile
    - make
    - gcc
    - gfortran
    
    # required dependencies
    - f90wrap
    - numpy
    - pandas
    - matplotlib
    - h5py
    - tqdm
    - gdal
    - scipy
    - pyyaml
