dt: 86_400
start_time: 2012-01-01 00:00
optim_start_time: 2012-01-01 10:00
end_time: 2012-01-31 23:00

active_cell_only: False
sparse_storage: False

simulation_only: True

read_qobs: False
qobs_directory: qobs

read_prcp: False
prcp_format: tiff
prcp_conversion_factor: 1
prcp_directory: prcp_tiff

read_pet: False
pet_format: tiff
pet_conversion_factor: 1
pet_directory: pet_tiff
daily_interannual_pet: True

default_parameters:
    
    cp: 198
    cft: 102
    lr: 62
