# This workflow will generate the documentation
name: Documentation

on:

    push:
    
    pull_request:
        branches:
        - main
        - maintenance/**
        
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    ubuntu:
        name: (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: ["ubuntu-20.04", "ubuntu-22.04"]
        steps:
        - uses: actions/checkout@v3
            
        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install build-essential make gcc gfortran gdal-bin libgdal-dev
            python -m pip install --upgrade pip
            if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
        - name: Build and Install
          run: |
            make
        
        - name: Generate Documentation
          run: |
            make doc
