# This workflow will perform unit tests
name: Unit Tests

on:

    push:
        branches:
        - main

    pull_request:
        branches:
        - main
        - maintenance/**
        
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    ubuntu:
        name: (${{ matrix.os }} - py-${{ matrix.python-version }})
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: ["ubuntu-22.04"]
            python-version: ['3.9']
            
        steps:
        - uses: actions/checkout@v3
        
        - name: Conda Setup
          uses: s-weigand/setup-conda@v1
          with:
            conda-channels: conda-forge
        
        - name: Install Conda Env
          shell: bash
          run: |
            conda env create -f environment-dev.yml
            source activate smash-dev
            conda install python=${{ matrix.python-version }}
        
        - name: Build and Install
          run: |
            source activate smash-dev
            make
        
        - name: Run Tests
          run: |
            source activate smash-dev
            make test
