# This workflow will perform unit tests
name: Unit Tests

on:

    push:
        branches:
        - main

    pull_request:
        branches:
        - main
        - maintenance/**
        
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    ubuntu:
        name: (${{ matrix.os }} - py-${{ matrix.python-version }})
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: ["ubuntu-22.04"]
            python-version: ['3.9']
            
        steps:
        - uses: actions/checkout@v3
        
        - name: Update
          run: |
            sudo apt-get update
            sudo apt-get -y install software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get update
        
        - name: Set up Python ${{ matrix.python-version }}
          run: |
            sudo apt-get install -y --no-install-recommends \
            python${{ matrix.python-version }} \
            python${{ matrix.python-version }}-dev \
            python${{ matrix.python-version }}-venv
            
        - name: Install dependencies
          run: |
            sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
            sudo apt-get update
            python${{ matrix.python-version }} -m venv test
            . test/bin/activate
            python -m pip install --upgrade pip
            pip install gdal==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"
            if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
        - name: Build and Install
          run: |
            . test/bin/activate
            make
        
        - name: Run Tests
          run: |
            . test/bin/activate
            make test
