# This workflow will perform unit tests
name: Unit Tests

on:

    push:
        branches:
        - main

    pull_request:
        branches:
        - main
        - maintenance/**
        
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    ubuntu:
        name: (${{ matrix.os }} - py-${{ matrix.python-version }})
        runs-on: ${{ matrix.os }}
        container: ghcr.io/osgeo/gdal:ubuntu-small-latest
        env:
          DEBIAN_FRONTEND: noninteractive
        strategy:
          matrix:
            os: ["ubuntu-22.04"]
            python-version: ['3.9']
            
        steps:
        - uses: actions/checkout@v3
            
        - name: Install dependencies
          run: |
            python3 --version
            python3 -c 'import gdal'
            python3 -c 'from osgeo import gdal'
        
        - name: Build and Install
          run: |
            make
        
        - name: Run Tests
          run: |
            make test
