# This workflow will perform unit tests
name: Unit Tests

on:

    push:
        branches:
        - main

    pull_request:
        branches:
        - main
        - maintenance/**
        
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    ubuntu:
        name: (${{ matrix.os }} - py-${{ matrix.python-version }})
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: ["ubuntu-22.04"]
            python-version: ['3.9']
            
        steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            update-environment: true
            
        - name: Install dependencies
          shell: bash
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential make gcc gfortran gdal-bin libgdal-dev libshp-dev python3-gdal python3-venv python3-dev
            python --version
            gdal-config --version
            python -m pip install --upgrade pip
            pip install gdal==3.4.1 --global-option=build_ext --global-option="-I/usr/include/gdal"
            python -c 'import gdal'
            python -c 'from osgeo import gdal'
        
        - name: Build and Install
          run: |
            make
        
        - name: Run Tests
          run: |
            make test
